version: 2

sources:
  - name: pokemon
    database: "{{ target.name }}_HACKATHON2"
    schema: TNT
    tables:
      - name: RAW_POKEMON_BASE
        meta:
          dagster:
            group: dbt
        description: "This table contains information about Pokémon, including their names and generations."
      - name: RAW_POKEMON_BATTLE
        meta:
          dagster:
            group: dbt
        description: "This table contains information about Pokemon battle stats."
      - name: RAW_POKEMON_REPRODUCTION
        meta:
          dagster:
            group: dbt
        description: "This table contains information about Pokemon reproduction, including encounter rate and egg stats."