pokemon_etl:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'externalbrowser') }}"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEM A', 'TNT')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"

      proxy_host: "{{ env_var('SNOWFLAKE_PROXY_HOST', '') }}"
      proxy_port: "{{ env_var('SNOWFLAKE_PROXY_PORT', '') | int }}"
 
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: false      
      threads: 4

    # prod:
    #   type: snowflake
    #   path: prod.duckdb
    #   threads: 4